# -*- coding: utf-8 -*-
"""Sentiment Analysis Oct 19, 2024, 3_06_39 PM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vctfPuAKw7kuTKjkjbQT-6KNorjSgIGe

1. Install the Vertex AI SDK: Open a terminal window and enter the command below. You can also [install it in a virtualenv](https://googleapis.dev/python/aiplatform/latest/index.html)
"""

!pip install --upgrade google-cloud-aiplatform

"""2. Use the following code in your application to request a model response"""

import base64
import vertexai
from vertexai.generative_models import GenerativeModel, Part, SafetySetting


def generate():
    vertexai.init(project="qwiklabs-gcp-03-a33317bb843a", location="us-west1")
    model = GenerativeModel(
        "gemini-1.5-flash-002",
    )
    responses = model.generate_content(
        [text1],
        generation_config=generation_config,
        safety_settings=safety_settings,
        stream=True,
    )

    for response in responses:
        print(response.text, end="")

text1 = """What is a prompt gallery?

input: A well-made and entertaining film
output: positive

input: I fell asleep after 10 minutes
output: 	negative

input: The movie was ok
output: neutral


input: It was a time well spent!
output:"""

generation_config = {
    "max_output_tokens": 3256,
    "temperature": 0,
    "top_p": 0.95,
}

safety_settings = [
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
]

generate()