# -*- coding: utf-8 -*-
"""Task 2. Build a Gemini tagline generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FgoZBbgJVRef9-V_UTFQql_X1fyYF8WB

1. Install the Vertex AI SDK: Open a terminal window and enter the command below. You can also install it in a virtualenv
"""

!pip install --upgrade google-cloud-aiplatform
!gcloud auth application-default login

"""2. Use the following code in your application to request a model response"""

import base64
import vertexai
from vertexai.generative_models import GenerativeModel, Part, SafetySetting


def generate():
    vertexai.init(project="qwiklabs-gcp-03-fa4c90d3be96", location="us-central1")
    model = GenerativeModel(
        "gemini-1.5-pro-002",
        system_instruction=[textsi_1]
    )
    responses = model.generate_content(
        [text1],
        generation_config=generation_config,
        safety_settings=safety_settings,
        stream=True,
    )

    for response in responses:
        print(response.text, end="")

text1 = """Input: Write a tagline for a durable backpack designed for hikers that makes them feel prepared. Consider styles like minimalist.
Output: Built for the Journey: Your Adventure Essentials.
Input: Create a tagline for a lightweight tent aimed at young adventurers that fosters a sense of freedom. Consider styles like adventurous.
Output: Sleep Under the Stars: Your Gateway to Adventure.
Prompt Structure:
Product Attributes: (e.g., durable, lightweight, waterproof)
Target Audience: (e.g., young adventurers, families, outdoor enthusiasts)
Emotional Resonance: (e.g., empowered, connected, adventurous)
Style Preferences: (e.g., minimalist, playful, inspiring)

Write a tagline for a durable backpack designed for hikers that makes them feel prepared. Consider styles like minimalist.: Product Attributes: Waterproof, comfortable; Target Audience: Families; Emotional Resonance: Connected
makes them feel prepared. Consider styles like minimalist.	Built for the Journey: Your Adventure Essentials.: Create lasting memories together with our weatherproof, comfortable gear."""
textsi_1 = """Cymbal Direct is partnering with an outdoor gear retailer. They\'re launching a new line of products designed to encourage young people to explore the outdoors. Help them create catchy taglines for this product line."""

generation_config = {
    "max_output_tokens": 4029,
    "temperature": 1.1,
    "top_p": 0.95,
}

safety_settings = [
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HATE_SPEECH,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_DANGEROUS_CONTENT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_SEXUALLY_EXPLICIT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
    SafetySetting(
        category=SafetySetting.HarmCategory.HARM_CATEGORY_HARASSMENT,
        threshold=SafetySetting.HarmBlockThreshold.OFF
    ),
]

generate()